/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "MEMBER" | "MANAGER" | "HR_ADMIN" | "TEACHER" | "BOD";
        Permission: {
            /** @enum {string} */
            action: "view" | "create" | "edit" | "deactivate" | "grade" | "approve" | "classify";
            /** @enum {string} */
            resource: "employee" | "exam" | "promotion" | "team" | "department" | "radar_chart" | "checklist" | "submission" | "kpi";
        };
        UserSession: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            permissions: components["schemas"]["Permission"][];
            /** Format: uuid */
            departmentId: string;
            teamIds: string[];
        };
        MeResponse: {
            user: components["schemas"]["UserSession"];
            accessToken: string;
        };
        Employee: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "PROBATION" | "RESERVED";
            /** Format: uuid */
            departmentId: string;
            teamIds: string[];
            /** @enum {string} */
            currentLevel: "tap_su" | "biet_viec" | "duoc_viec" | "dong_gop_ket_qua" | "tuong";
            currentStar: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateEmployeeInput: {
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            departmentId: string;
            /** Format: uuid */
            teamId: string;
            phone?: string;
            birthDate?: string;
        };
        ExamResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            examId: string;
            /** Format: uuid */
            employeeId: string;
            /** @enum {string} */
            result: "DAT" | "BAO_LUU" | "CHO_HOC_LAI" | "CHIA_TAY";
            /** Format: date-time */
            classifiedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
