/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bắt đầu OAuth Google (redirect) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect tới Google */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback (redirect, set cookie) */
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect về FRONTEND_URL/login?oauth=success|error */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất (xóa cookie session) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phiên hiện tại */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "MEMBER" | "LEADER" | "MANAGER" | "HR" | "TEACHER" | "BOD";
        Permission: {
            /** @enum {string} */
            action: "view" | "create" | "edit" | "deactivate" | "grade" | "approve" | "classify";
            /** @enum {string} */
            resource: "employee" | "exam" | "promotion" | "team" | "department" | "radar_chart" | "checklist" | "submission" | "kpi" | "okr" | "monthly_report";
        };
        UserSession: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** @description Đa vai trò (RBAC động); khi có thì union quyền theo các role + permissionIds. */
            roles?: components["schemas"]["Role"][];
            permissions: components["schemas"]["Permission"][];
            /** @description Quyền chức năng theo id catalog (chuỗi ổn định, ví dụ hr.employees.view). */
            permissionIds?: string[];
            /** @description Cờ giới hạn dữ liệu (ABAC), ví dụ chỉ xem bản ghi phụ trách. */
            dataScopeFlags?: {
                [key: string]: boolean;
            };
            /** Format: uuid */
            departmentId: string;
            teamIds: string[];
        };
        MeResponse: {
            user: components["schemas"]["UserSession"];
            accessToken?: string;
        };
        Employee: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "PROBATION" | "RESERVED" | "TRANSFERRED";
            /** Format: uuid */
            departmentId: string;
            teamIds: string[];
            /** @enum {string} */
            currentLevel: "tap_su" | "biet_viec" | "duoc_viec" | "dong_gop_ket_qua" | "tuong";
            currentStar: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            phone?: string | null;
            birthDate?: string | null;
            /** @description Ngày bắt đầu (start_date_work) */
            startDate?: string | null;
        };
        CreateEmployeeInput: {
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            departmentId: string;
            /** Format: uuid */
            teamId: string;
            /** @description Nhóm bổ sung (ngoài teamId theo phòng ban) */
            extraTeamIds?: string[];
            phone?: string;
            birthDate?: string;
            /** @description Ngày bắt đầu làm việc (start_date_work) */
            startDate?: string;
            /** @enum {string} */
            initialLevel?: "tap_su" | "biet_viec" | "duoc_viec" | "dong_gop_ket_qua" | "tuong";
            /** @description false = không gửi email thông báo tạo tài khoản */
            notifyEmail?: boolean;
            displayName?: string;
            gender?: string;
            facebookUrl?: string;
            jobTitle?: string;
            teamPosition?: string;
            workplaceBranch?: string;
            directManager?: string | null;
            addressCurrent?: string;
            addressHousehold?: string;
            educationLevel?: string;
            schoolName?: string;
            hometownDetail?: string;
            identityDocumentInfo?: string;
            maritalStatus?: string;
            ethnicity?: string;
            religion?: string;
            insuranceBookNumber?: string;
            childrenInfo?: string;
            emergencyContact1?: string;
            emergencyContact2?: string;
            fatherGuardianContact?: string;
            motherGuardianContact?: string;
            familyNotes?: string;
            bankAccountInfo?: string;
            vehicleInfo?: string;
            managerBlockCode?: string;
            attachmentIdFront?: string;
            attachmentIdBack?: string;
            policyAcknowledgement?: string;
            profileReviewDate?: string;
            cvAttachmentRef?: string;
            notes?: string;
        };
        PatchEmployeeInput: {
            name?: string;
            /** Format: email */
            email?: string;
            role?: components["schemas"]["Role"];
            /** Format: uuid */
            departmentId?: string;
            /** Format: uuid */
            teamId?: string;
            /** @description Nhóm bổ sung (ngoài teamId theo phòng ban) */
            extraTeamIds?: string[];
            phone?: string;
            birthDate?: string;
            /** @description Ngày bắt đầu làm việc */
            startDate?: string;
            /** @description UUID team phụ trên FE; gửi chuỗi rỗng để xóa */
            secondaryTeamId?: string;
            directManager?: string | null;
            /** @enum {string} */
            currentLevel?: "tap_su" | "biet_viec" | "duoc_viec" | "dong_gop_ket_qua" | "tuong";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "PROBATION" | "RESERVED" | "TRANSFERRED";
        };
        ExamResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            examId: string;
            /** Format: uuid */
            employeeId: string;
            /** @enum {string} */
            result: "DAT" | "BAO_LUU" | "CHO_HOC_LAI" | "CHIA_TAY";
            /** Format: date-time */
            classifiedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
