/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedMonthlyReportRouteImport } from './routes/_protected/monthly-report'
import { Route as ProtectedLearningScheduleRouteImport } from './routes/_protected/learning-schedule'
import { Route as ProtectedLearningClassesRouteImport } from './routes/_protected/learning-classes'
import { Route as ProtectedKpiOkrRouteImport } from './routes/_protected/kpi-okr'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedPermissionsIndexRouteImport } from './routes/_protected/permissions/index'
import { Route as ProtectedLearningPathIndexRouteImport } from './routes/_protected/learning-path/index'
import { Route as ProtectedHrAdminIndexRouteImport } from './routes/_protected/hr-admin/index'
import { Route as ProtectedExamIndexRouteImport } from './routes/_protected/exam/index'
import { Route as ProtectedPermissionsEmployeeIdRouteImport } from './routes/_protected/permissions/$employeeId'
import { Route as ProtectedManagerTeamProgressRouteImport } from './routes/_protected/manager/team-progress'
import { Route as ProtectedManagerReviewSubmissionsRouteImport } from './routes/_protected/manager/review-submissions'
import { Route as ProtectedManagerExercisesRouteImport } from './routes/_protected/manager/exercises'
import { Route as ProtectedManagerExamScheduleRouteImport } from './routes/_protected/manager/exam-schedule'
import { Route as ProtectedManagerClassesRouteImport } from './routes/_protected/manager/classes'
import { Route as ProtectedManagerApprovalsRouteImport } from './routes/_protected/manager/approvals'
import { Route as ProtectedLeaderKpiOkrRouteImport } from './routes/_protected/leader/kpi-okr'
import { Route as ProtectedHrAdminNewRouteImport } from './routes/_protected/hr-admin/new'
import { Route as ProtectedHrAdminEmployeeIdRouteImport } from './routes/_protected/hr-admin/$employeeId'
import { Route as ProtectedExamGraderRouteImport } from './routes/_protected/exam/grader'
import { Route as ProtectedBodTraineeRankingRouteImport } from './routes/_protected/bod/trainee-ranking'
import { Route as ProtectedBodTeamComparisonRouteImport } from './routes/_protected/bod/team-comparison'
import { Route as ProtectedBodDashboardRouteImport } from './routes/_protected/bod/dashboard'
import { Route as ProtectedTeacherClassesIndexRouteImport } from './routes/_protected/teacher/classes/index'
import { Route as ProtectedLeaderTeamIndexRouteImport } from './routes/_protected/leader/team/index'
import { Route as ProtectedTeacherClassesClassIdRouteImport } from './routes/_protected/teacher/classes/$classId'
import { Route as ProtectedManagerTeamEmployeeIdRouteImport } from './routes/_protected/manager/team/$employeeId'
import { Route as ProtectedLearningPathLevelIdStarIdRouteImport } from './routes/_protected/learning-path/$levelId/$starId'
import { Route as ProtectedLeaderTeamEmployeeIdRouteImport } from './routes/_protected/leader/team/$employeeId'
import { Route as ProtectedExamExamIdResultRouteImport } from './routes/_protected/exam/$examId/result'
import { Route as ProtectedExamExamIdGradeRouteImport } from './routes/_protected/exam/$examId/grade'
import { Route as ProtectedExamExamIdClassifyRouteImport } from './routes/_protected/exam/$examId/classify'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMonthlyReportRoute = ProtectedMonthlyReportRouteImport.update({
  id: '/monthly-report',
  path: '/monthly-report',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLearningScheduleRoute =
  ProtectedLearningScheduleRouteImport.update({
    id: '/learning-schedule',
    path: '/learning-schedule',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLearningClassesRoute =
  ProtectedLearningClassesRouteImport.update({
    id: '/learning-classes',
    path: '/learning-classes',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKpiOkrRoute = ProtectedKpiOkrRouteImport.update({
  id: '/kpi-okr',
  path: '/kpi-okr',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedPermissionsIndexRoute =
  ProtectedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLearningPathIndexRoute =
  ProtectedLearningPathIndexRouteImport.update({
    id: '/learning-path/',
    path: '/learning-path/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrAdminIndexRoute = ProtectedHrAdminIndexRouteImport.update({
  id: '/hr-admin/',
  path: '/hr-admin/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExamIndexRoute = ProtectedExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPermissionsEmployeeIdRoute =
  ProtectedPermissionsEmployeeIdRouteImport.update({
    id: '/permissions/$employeeId',
    path: '/permissions/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerTeamProgressRoute =
  ProtectedManagerTeamProgressRouteImport.update({
    id: '/manager/team-progress',
    path: '/manager/team-progress',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerReviewSubmissionsRoute =
  ProtectedManagerReviewSubmissionsRouteImport.update({
    id: '/manager/review-submissions',
    path: '/manager/review-submissions',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerExercisesRoute =
  ProtectedManagerExercisesRouteImport.update({
    id: '/manager/exercises',
    path: '/manager/exercises',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerExamScheduleRoute =
  ProtectedManagerExamScheduleRouteImport.update({
    id: '/manager/exam-schedule',
    path: '/manager/exam-schedule',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerClassesRoute = ProtectedManagerClassesRouteImport.update({
  id: '/manager/classes',
  path: '/manager/classes',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedManagerApprovalsRoute =
  ProtectedManagerApprovalsRouteImport.update({
    id: '/manager/approvals',
    path: '/manager/approvals',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeaderKpiOkrRoute = ProtectedLeaderKpiOkrRouteImport.update({
  id: '/leader/kpi-okr',
  path: '/leader/kpi-okr',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHrAdminNewRoute = ProtectedHrAdminNewRouteImport.update({
  id: '/hr-admin/new',
  path: '/hr-admin/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHrAdminEmployeeIdRoute =
  ProtectedHrAdminEmployeeIdRouteImport.update({
    id: '/hr-admin/$employeeId',
    path: '/hr-admin/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedExamGraderRoute = ProtectedExamGraderRouteImport.update({
  id: '/exam/grader',
  path: '/exam/grader',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBodTraineeRankingRoute =
  ProtectedBodTraineeRankingRouteImport.update({
    id: '/bod/trainee-ranking',
    path: '/bod/trainee-ranking',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedBodTeamComparisonRoute =
  ProtectedBodTeamComparisonRouteImport.update({
    id: '/bod/team-comparison',
    path: '/bod/team-comparison',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedBodDashboardRoute = ProtectedBodDashboardRouteImport.update({
  id: '/bod/dashboard',
  path: '/bod/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTeacherClassesIndexRoute =
  ProtectedTeacherClassesIndexRouteImport.update({
    id: '/teacher/classes/',
    path: '/teacher/classes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeaderTeamIndexRoute =
  ProtectedLeaderTeamIndexRouteImport.update({
    id: '/leader/team/',
    path: '/leader/team/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedTeacherClassesClassIdRoute =
  ProtectedTeacherClassesClassIdRouteImport.update({
    id: '/teacher/classes/$classId',
    path: '/teacher/classes/$classId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManagerTeamEmployeeIdRoute =
  ProtectedManagerTeamEmployeeIdRouteImport.update({
    id: '/manager/team/$employeeId',
    path: '/manager/team/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLearningPathLevelIdStarIdRoute =
  ProtectedLearningPathLevelIdStarIdRouteImport.update({
    id: '/learning-path/$levelId/$starId',
    path: '/learning-path/$levelId/$starId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeaderTeamEmployeeIdRoute =
  ProtectedLeaderTeamEmployeeIdRouteImport.update({
    id: '/leader/team/$employeeId',
    path: '/leader/team/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedExamExamIdResultRoute =
  ProtectedExamExamIdResultRouteImport.update({
    id: '/exam/$examId/result',
    path: '/exam/$examId/result',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedExamExamIdGradeRoute =
  ProtectedExamExamIdGradeRouteImport.update({
    id: '/exam/$examId/grade',
    path: '/exam/$examId/grade',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedExamExamIdClassifyRoute =
  ProtectedExamExamIdClassifyRouteImport.update({
    id: '/exam/$examId/classify',
    path: '/exam/$examId/classify',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/kpi-okr': typeof ProtectedKpiOkrRoute
  '/learning-classes': typeof ProtectedLearningClassesRoute
  '/learning-schedule': typeof ProtectedLearningScheduleRoute
  '/monthly-report': typeof ProtectedMonthlyReportRoute
  '/profile': typeof ProtectedProfileRoute
  '/bod/dashboard': typeof ProtectedBodDashboardRoute
  '/bod/team-comparison': typeof ProtectedBodTeamComparisonRoute
  '/bod/trainee-ranking': typeof ProtectedBodTraineeRankingRoute
  '/exam/grader': typeof ProtectedExamGraderRoute
  '/hr-admin/$employeeId': typeof ProtectedHrAdminEmployeeIdRoute
  '/hr-admin/new': typeof ProtectedHrAdminNewRoute
  '/leader/kpi-okr': typeof ProtectedLeaderKpiOkrRoute
  '/manager/approvals': typeof ProtectedManagerApprovalsRoute
  '/manager/classes': typeof ProtectedManagerClassesRoute
  '/manager/exam-schedule': typeof ProtectedManagerExamScheduleRoute
  '/manager/exercises': typeof ProtectedManagerExercisesRoute
  '/manager/review-submissions': typeof ProtectedManagerReviewSubmissionsRoute
  '/manager/team-progress': typeof ProtectedManagerTeamProgressRoute
  '/permissions/$employeeId': typeof ProtectedPermissionsEmployeeIdRoute
  '/exam/': typeof ProtectedExamIndexRoute
  '/hr-admin/': typeof ProtectedHrAdminIndexRoute
  '/learning-path/': typeof ProtectedLearningPathIndexRoute
  '/permissions/': typeof ProtectedPermissionsIndexRoute
  '/exam/$examId/classify': typeof ProtectedExamExamIdClassifyRoute
  '/exam/$examId/grade': typeof ProtectedExamExamIdGradeRoute
  '/exam/$examId/result': typeof ProtectedExamExamIdResultRoute
  '/leader/team/$employeeId': typeof ProtectedLeaderTeamEmployeeIdRoute
  '/learning-path/$levelId/$starId': typeof ProtectedLearningPathLevelIdStarIdRoute
  '/manager/team/$employeeId': typeof ProtectedManagerTeamEmployeeIdRoute
  '/teacher/classes/$classId': typeof ProtectedTeacherClassesClassIdRoute
  '/leader/team/': typeof ProtectedLeaderTeamIndexRoute
  '/teacher/classes/': typeof ProtectedTeacherClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/kpi-okr': typeof ProtectedKpiOkrRoute
  '/learning-classes': typeof ProtectedLearningClassesRoute
  '/learning-schedule': typeof ProtectedLearningScheduleRoute
  '/monthly-report': typeof ProtectedMonthlyReportRoute
  '/profile': typeof ProtectedProfileRoute
  '/bod/dashboard': typeof ProtectedBodDashboardRoute
  '/bod/team-comparison': typeof ProtectedBodTeamComparisonRoute
  '/bod/trainee-ranking': typeof ProtectedBodTraineeRankingRoute
  '/exam/grader': typeof ProtectedExamGraderRoute
  '/hr-admin/$employeeId': typeof ProtectedHrAdminEmployeeIdRoute
  '/hr-admin/new': typeof ProtectedHrAdminNewRoute
  '/leader/kpi-okr': typeof ProtectedLeaderKpiOkrRoute
  '/manager/approvals': typeof ProtectedManagerApprovalsRoute
  '/manager/classes': typeof ProtectedManagerClassesRoute
  '/manager/exam-schedule': typeof ProtectedManagerExamScheduleRoute
  '/manager/exercises': typeof ProtectedManagerExercisesRoute
  '/manager/review-submissions': typeof ProtectedManagerReviewSubmissionsRoute
  '/manager/team-progress': typeof ProtectedManagerTeamProgressRoute
  '/permissions/$employeeId': typeof ProtectedPermissionsEmployeeIdRoute
  '/exam': typeof ProtectedExamIndexRoute
  '/hr-admin': typeof ProtectedHrAdminIndexRoute
  '/learning-path': typeof ProtectedLearningPathIndexRoute
  '/permissions': typeof ProtectedPermissionsIndexRoute
  '/exam/$examId/classify': typeof ProtectedExamExamIdClassifyRoute
  '/exam/$examId/grade': typeof ProtectedExamExamIdGradeRoute
  '/exam/$examId/result': typeof ProtectedExamExamIdResultRoute
  '/leader/team/$employeeId': typeof ProtectedLeaderTeamEmployeeIdRoute
  '/learning-path/$levelId/$starId': typeof ProtectedLearningPathLevelIdStarIdRoute
  '/manager/team/$employeeId': typeof ProtectedManagerTeamEmployeeIdRoute
  '/teacher/classes/$classId': typeof ProtectedTeacherClassesClassIdRoute
  '/leader/team': typeof ProtectedLeaderTeamIndexRoute
  '/teacher/classes': typeof ProtectedTeacherClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/kpi-okr': typeof ProtectedKpiOkrRoute
  '/_protected/learning-classes': typeof ProtectedLearningClassesRoute
  '/_protected/learning-schedule': typeof ProtectedLearningScheduleRoute
  '/_protected/monthly-report': typeof ProtectedMonthlyReportRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/bod/dashboard': typeof ProtectedBodDashboardRoute
  '/_protected/bod/team-comparison': typeof ProtectedBodTeamComparisonRoute
  '/_protected/bod/trainee-ranking': typeof ProtectedBodTraineeRankingRoute
  '/_protected/exam/grader': typeof ProtectedExamGraderRoute
  '/_protected/hr-admin/$employeeId': typeof ProtectedHrAdminEmployeeIdRoute
  '/_protected/hr-admin/new': typeof ProtectedHrAdminNewRoute
  '/_protected/leader/kpi-okr': typeof ProtectedLeaderKpiOkrRoute
  '/_protected/manager/approvals': typeof ProtectedManagerApprovalsRoute
  '/_protected/manager/classes': typeof ProtectedManagerClassesRoute
  '/_protected/manager/exam-schedule': typeof ProtectedManagerExamScheduleRoute
  '/_protected/manager/exercises': typeof ProtectedManagerExercisesRoute
  '/_protected/manager/review-submissions': typeof ProtectedManagerReviewSubmissionsRoute
  '/_protected/manager/team-progress': typeof ProtectedManagerTeamProgressRoute
  '/_protected/permissions/$employeeId': typeof ProtectedPermissionsEmployeeIdRoute
  '/_protected/exam/': typeof ProtectedExamIndexRoute
  '/_protected/hr-admin/': typeof ProtectedHrAdminIndexRoute
  '/_protected/learning-path/': typeof ProtectedLearningPathIndexRoute
  '/_protected/permissions/': typeof ProtectedPermissionsIndexRoute
  '/_protected/exam/$examId/classify': typeof ProtectedExamExamIdClassifyRoute
  '/_protected/exam/$examId/grade': typeof ProtectedExamExamIdGradeRoute
  '/_protected/exam/$examId/result': typeof ProtectedExamExamIdResultRoute
  '/_protected/leader/team/$employeeId': typeof ProtectedLeaderTeamEmployeeIdRoute
  '/_protected/learning-path/$levelId/$starId': typeof ProtectedLearningPathLevelIdStarIdRoute
  '/_protected/manager/team/$employeeId': typeof ProtectedManagerTeamEmployeeIdRoute
  '/_protected/teacher/classes/$classId': typeof ProtectedTeacherClassesClassIdRoute
  '/_protected/leader/team/': typeof ProtectedLeaderTeamIndexRoute
  '/_protected/teacher/classes/': typeof ProtectedTeacherClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kpi-okr'
    | '/learning-classes'
    | '/learning-schedule'
    | '/monthly-report'
    | '/profile'
    | '/bod/dashboard'
    | '/bod/team-comparison'
    | '/bod/trainee-ranking'
    | '/exam/grader'
    | '/hr-admin/$employeeId'
    | '/hr-admin/new'
    | '/leader/kpi-okr'
    | '/manager/approvals'
    | '/manager/classes'
    | '/manager/exam-schedule'
    | '/manager/exercises'
    | '/manager/review-submissions'
    | '/manager/team-progress'
    | '/permissions/$employeeId'
    | '/exam/'
    | '/hr-admin/'
    | '/learning-path/'
    | '/permissions/'
    | '/exam/$examId/classify'
    | '/exam/$examId/grade'
    | '/exam/$examId/result'
    | '/leader/team/$employeeId'
    | '/learning-path/$levelId/$starId'
    | '/manager/team/$employeeId'
    | '/teacher/classes/$classId'
    | '/leader/team/'
    | '/teacher/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kpi-okr'
    | '/learning-classes'
    | '/learning-schedule'
    | '/monthly-report'
    | '/profile'
    | '/bod/dashboard'
    | '/bod/team-comparison'
    | '/bod/trainee-ranking'
    | '/exam/grader'
    | '/hr-admin/$employeeId'
    | '/hr-admin/new'
    | '/leader/kpi-okr'
    | '/manager/approvals'
    | '/manager/classes'
    | '/manager/exam-schedule'
    | '/manager/exercises'
    | '/manager/review-submissions'
    | '/manager/team-progress'
    | '/permissions/$employeeId'
    | '/exam'
    | '/hr-admin'
    | '/learning-path'
    | '/permissions'
    | '/exam/$examId/classify'
    | '/exam/$examId/grade'
    | '/exam/$examId/result'
    | '/leader/team/$employeeId'
    | '/learning-path/$levelId/$starId'
    | '/manager/team/$employeeId'
    | '/teacher/classes/$classId'
    | '/leader/team'
    | '/teacher/classes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/dashboard'
    | '/_protected/kpi-okr'
    | '/_protected/learning-classes'
    | '/_protected/learning-schedule'
    | '/_protected/monthly-report'
    | '/_protected/profile'
    | '/_protected/bod/dashboard'
    | '/_protected/bod/team-comparison'
    | '/_protected/bod/trainee-ranking'
    | '/_protected/exam/grader'
    | '/_protected/hr-admin/$employeeId'
    | '/_protected/hr-admin/new'
    | '/_protected/leader/kpi-okr'
    | '/_protected/manager/approvals'
    | '/_protected/manager/classes'
    | '/_protected/manager/exam-schedule'
    | '/_protected/manager/exercises'
    | '/_protected/manager/review-submissions'
    | '/_protected/manager/team-progress'
    | '/_protected/permissions/$employeeId'
    | '/_protected/exam/'
    | '/_protected/hr-admin/'
    | '/_protected/learning-path/'
    | '/_protected/permissions/'
    | '/_protected/exam/$examId/classify'
    | '/_protected/exam/$examId/grade'
    | '/_protected/exam/$examId/result'
    | '/_protected/leader/team/$employeeId'
    | '/_protected/learning-path/$levelId/$starId'
    | '/_protected/manager/team/$employeeId'
    | '/_protected/teacher/classes/$classId'
    | '/_protected/leader/team/'
    | '/_protected/teacher/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/monthly-report': {
      id: '/_protected/monthly-report'
      path: '/monthly-report'
      fullPath: '/monthly-report'
      preLoaderRoute: typeof ProtectedMonthlyReportRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/learning-schedule': {
      id: '/_protected/learning-schedule'
      path: '/learning-schedule'
      fullPath: '/learning-schedule'
      preLoaderRoute: typeof ProtectedLearningScheduleRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/learning-classes': {
      id: '/_protected/learning-classes'
      path: '/learning-classes'
      fullPath: '/learning-classes'
      preLoaderRoute: typeof ProtectedLearningClassesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/kpi-okr': {
      id: '/_protected/kpi-okr'
      path: '/kpi-okr'
      fullPath: '/kpi-okr'
      preLoaderRoute: typeof ProtectedKpiOkrRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/permissions/': {
      id: '/_protected/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof ProtectedPermissionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/learning-path/': {
      id: '/_protected/learning-path/'
      path: '/learning-path'
      fullPath: '/learning-path/'
      preLoaderRoute: typeof ProtectedLearningPathIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr-admin/': {
      id: '/_protected/hr-admin/'
      path: '/hr-admin'
      fullPath: '/hr-admin/'
      preLoaderRoute: typeof ProtectedHrAdminIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exam/': {
      id: '/_protected/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ProtectedExamIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/permissions/$employeeId': {
      id: '/_protected/permissions/$employeeId'
      path: '/permissions/$employeeId'
      fullPath: '/permissions/$employeeId'
      preLoaderRoute: typeof ProtectedPermissionsEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/team-progress': {
      id: '/_protected/manager/team-progress'
      path: '/manager/team-progress'
      fullPath: '/manager/team-progress'
      preLoaderRoute: typeof ProtectedManagerTeamProgressRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/review-submissions': {
      id: '/_protected/manager/review-submissions'
      path: '/manager/review-submissions'
      fullPath: '/manager/review-submissions'
      preLoaderRoute: typeof ProtectedManagerReviewSubmissionsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/exercises': {
      id: '/_protected/manager/exercises'
      path: '/manager/exercises'
      fullPath: '/manager/exercises'
      preLoaderRoute: typeof ProtectedManagerExercisesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/exam-schedule': {
      id: '/_protected/manager/exam-schedule'
      path: '/manager/exam-schedule'
      fullPath: '/manager/exam-schedule'
      preLoaderRoute: typeof ProtectedManagerExamScheduleRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/classes': {
      id: '/_protected/manager/classes'
      path: '/manager/classes'
      fullPath: '/manager/classes'
      preLoaderRoute: typeof ProtectedManagerClassesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/approvals': {
      id: '/_protected/manager/approvals'
      path: '/manager/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof ProtectedManagerApprovalsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leader/kpi-okr': {
      id: '/_protected/leader/kpi-okr'
      path: '/leader/kpi-okr'
      fullPath: '/leader/kpi-okr'
      preLoaderRoute: typeof ProtectedLeaderKpiOkrRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr-admin/new': {
      id: '/_protected/hr-admin/new'
      path: '/hr-admin/new'
      fullPath: '/hr-admin/new'
      preLoaderRoute: typeof ProtectedHrAdminNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr-admin/$employeeId': {
      id: '/_protected/hr-admin/$employeeId'
      path: '/hr-admin/$employeeId'
      fullPath: '/hr-admin/$employeeId'
      preLoaderRoute: typeof ProtectedHrAdminEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exam/grader': {
      id: '/_protected/exam/grader'
      path: '/exam/grader'
      fullPath: '/exam/grader'
      preLoaderRoute: typeof ProtectedExamGraderRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bod/trainee-ranking': {
      id: '/_protected/bod/trainee-ranking'
      path: '/bod/trainee-ranking'
      fullPath: '/bod/trainee-ranking'
      preLoaderRoute: typeof ProtectedBodTraineeRankingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bod/team-comparison': {
      id: '/_protected/bod/team-comparison'
      path: '/bod/team-comparison'
      fullPath: '/bod/team-comparison'
      preLoaderRoute: typeof ProtectedBodTeamComparisonRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bod/dashboard': {
      id: '/_protected/bod/dashboard'
      path: '/bod/dashboard'
      fullPath: '/bod/dashboard'
      preLoaderRoute: typeof ProtectedBodDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/teacher/classes/': {
      id: '/_protected/teacher/classes/'
      path: '/teacher/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof ProtectedTeacherClassesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leader/team/': {
      id: '/_protected/leader/team/'
      path: '/leader/team'
      fullPath: '/leader/team/'
      preLoaderRoute: typeof ProtectedLeaderTeamIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/teacher/classes/$classId': {
      id: '/_protected/teacher/classes/$classId'
      path: '/teacher/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof ProtectedTeacherClassesClassIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manager/team/$employeeId': {
      id: '/_protected/manager/team/$employeeId'
      path: '/manager/team/$employeeId'
      fullPath: '/manager/team/$employeeId'
      preLoaderRoute: typeof ProtectedManagerTeamEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/learning-path/$levelId/$starId': {
      id: '/_protected/learning-path/$levelId/$starId'
      path: '/learning-path/$levelId/$starId'
      fullPath: '/learning-path/$levelId/$starId'
      preLoaderRoute: typeof ProtectedLearningPathLevelIdStarIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leader/team/$employeeId': {
      id: '/_protected/leader/team/$employeeId'
      path: '/leader/team/$employeeId'
      fullPath: '/leader/team/$employeeId'
      preLoaderRoute: typeof ProtectedLeaderTeamEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exam/$examId/result': {
      id: '/_protected/exam/$examId/result'
      path: '/exam/$examId/result'
      fullPath: '/exam/$examId/result'
      preLoaderRoute: typeof ProtectedExamExamIdResultRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exam/$examId/grade': {
      id: '/_protected/exam/$examId/grade'
      path: '/exam/$examId/grade'
      fullPath: '/exam/$examId/grade'
      preLoaderRoute: typeof ProtectedExamExamIdGradeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exam/$examId/classify': {
      id: '/_protected/exam/$examId/classify'
      path: '/exam/$examId/classify'
      fullPath: '/exam/$examId/classify'
      preLoaderRoute: typeof ProtectedExamExamIdClassifyRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedKpiOkrRoute: typeof ProtectedKpiOkrRoute
  ProtectedLearningClassesRoute: typeof ProtectedLearningClassesRoute
  ProtectedLearningScheduleRoute: typeof ProtectedLearningScheduleRoute
  ProtectedMonthlyReportRoute: typeof ProtectedMonthlyReportRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedBodDashboardRoute: typeof ProtectedBodDashboardRoute
  ProtectedBodTeamComparisonRoute: typeof ProtectedBodTeamComparisonRoute
  ProtectedBodTraineeRankingRoute: typeof ProtectedBodTraineeRankingRoute
  ProtectedExamGraderRoute: typeof ProtectedExamGraderRoute
  ProtectedHrAdminEmployeeIdRoute: typeof ProtectedHrAdminEmployeeIdRoute
  ProtectedHrAdminNewRoute: typeof ProtectedHrAdminNewRoute
  ProtectedLeaderKpiOkrRoute: typeof ProtectedLeaderKpiOkrRoute
  ProtectedManagerApprovalsRoute: typeof ProtectedManagerApprovalsRoute
  ProtectedManagerClassesRoute: typeof ProtectedManagerClassesRoute
  ProtectedManagerExamScheduleRoute: typeof ProtectedManagerExamScheduleRoute
  ProtectedManagerExercisesRoute: typeof ProtectedManagerExercisesRoute
  ProtectedManagerReviewSubmissionsRoute: typeof ProtectedManagerReviewSubmissionsRoute
  ProtectedManagerTeamProgressRoute: typeof ProtectedManagerTeamProgressRoute
  ProtectedPermissionsEmployeeIdRoute: typeof ProtectedPermissionsEmployeeIdRoute
  ProtectedExamIndexRoute: typeof ProtectedExamIndexRoute
  ProtectedHrAdminIndexRoute: typeof ProtectedHrAdminIndexRoute
  ProtectedLearningPathIndexRoute: typeof ProtectedLearningPathIndexRoute
  ProtectedPermissionsIndexRoute: typeof ProtectedPermissionsIndexRoute
  ProtectedExamExamIdClassifyRoute: typeof ProtectedExamExamIdClassifyRoute
  ProtectedExamExamIdGradeRoute: typeof ProtectedExamExamIdGradeRoute
  ProtectedExamExamIdResultRoute: typeof ProtectedExamExamIdResultRoute
  ProtectedLeaderTeamEmployeeIdRoute: typeof ProtectedLeaderTeamEmployeeIdRoute
  ProtectedLearningPathLevelIdStarIdRoute: typeof ProtectedLearningPathLevelIdStarIdRoute
  ProtectedManagerTeamEmployeeIdRoute: typeof ProtectedManagerTeamEmployeeIdRoute
  ProtectedTeacherClassesClassIdRoute: typeof ProtectedTeacherClassesClassIdRoute
  ProtectedLeaderTeamIndexRoute: typeof ProtectedLeaderTeamIndexRoute
  ProtectedTeacherClassesIndexRoute: typeof ProtectedTeacherClassesIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedKpiOkrRoute: ProtectedKpiOkrRoute,
  ProtectedLearningClassesRoute: ProtectedLearningClassesRoute,
  ProtectedLearningScheduleRoute: ProtectedLearningScheduleRoute,
  ProtectedMonthlyReportRoute: ProtectedMonthlyReportRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedBodDashboardRoute: ProtectedBodDashboardRoute,
  ProtectedBodTeamComparisonRoute: ProtectedBodTeamComparisonRoute,
  ProtectedBodTraineeRankingRoute: ProtectedBodTraineeRankingRoute,
  ProtectedExamGraderRoute: ProtectedExamGraderRoute,
  ProtectedHrAdminEmployeeIdRoute: ProtectedHrAdminEmployeeIdRoute,
  ProtectedHrAdminNewRoute: ProtectedHrAdminNewRoute,
  ProtectedLeaderKpiOkrRoute: ProtectedLeaderKpiOkrRoute,
  ProtectedManagerApprovalsRoute: ProtectedManagerApprovalsRoute,
  ProtectedManagerClassesRoute: ProtectedManagerClassesRoute,
  ProtectedManagerExamScheduleRoute: ProtectedManagerExamScheduleRoute,
  ProtectedManagerExercisesRoute: ProtectedManagerExercisesRoute,
  ProtectedManagerReviewSubmissionsRoute:
    ProtectedManagerReviewSubmissionsRoute,
  ProtectedManagerTeamProgressRoute: ProtectedManagerTeamProgressRoute,
  ProtectedPermissionsEmployeeIdRoute: ProtectedPermissionsEmployeeIdRoute,
  ProtectedExamIndexRoute: ProtectedExamIndexRoute,
  ProtectedHrAdminIndexRoute: ProtectedHrAdminIndexRoute,
  ProtectedLearningPathIndexRoute: ProtectedLearningPathIndexRoute,
  ProtectedPermissionsIndexRoute: ProtectedPermissionsIndexRoute,
  ProtectedExamExamIdClassifyRoute: ProtectedExamExamIdClassifyRoute,
  ProtectedExamExamIdGradeRoute: ProtectedExamExamIdGradeRoute,
  ProtectedExamExamIdResultRoute: ProtectedExamExamIdResultRoute,
  ProtectedLeaderTeamEmployeeIdRoute: ProtectedLeaderTeamEmployeeIdRoute,
  ProtectedLearningPathLevelIdStarIdRoute:
    ProtectedLearningPathLevelIdStarIdRoute,
  ProtectedManagerTeamEmployeeIdRoute: ProtectedManagerTeamEmployeeIdRoute,
  ProtectedTeacherClassesClassIdRoute: ProtectedTeacherClassesClassIdRoute,
  ProtectedLeaderTeamIndexRoute: ProtectedLeaderTeamIndexRoute,
  ProtectedTeacherClassesIndexRoute: ProtectedTeacherClassesIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
