#!/usr/bin/env python3
path = '/Users/macbook/TalentManagement/TalentManagement_FE/src/features/room-booking/RoomBookingSidebar.tsx'
ot, ct = chr(60), chr(62)
d = 'div'

def T(n, a=''):
    return f'{ot}{n}{(" " + a) if a else ""}{ct}'

def TC(n):
    return f'{ot}/{n}{ct}'

lines = []
a = lines.append

a("import { CheckCircle2, Clock, Loader2, X } from 'lucide-react'")
a("import type { MeetingBooking } from './api'")
a("import { formatDateVi, padTime } from './roomBookingTimeUtils'")
a("")
a("type PendingProps = {")
a("  items: MeetingBooking[]")
a("  processingId: string | null")
a("  onApprove: (id: string) => void")
a("  onReject: (id: string) => void")
a("}")
a("")
a("export function RoomBookingPendingPanel({")
a("  items,")
a("  processingId,")
a("  onApprove,")
a("  onReject,")
a("}: PendingProps) {")
a("  if (items.length === 0) {")
a("    return (")
a('      ' + T(d, 'className="rounded-2xl border border-border/60 bg-card p-4"'))
a('        <h3 className="text-sm font-bold text-foreground">Yêu cầu chờ duyệt</h3>')
a('        <p className="mt-2 text-xs text-muted-foreground">Không có yêu cầu nào.</p>')
a('      ' + TC(d))
a("    )")
a("  }")
a("  return (")
a('    ' + T(d, 'className="rounded-2xl border border-border/60 bg-card p-4"'))
a('      <h3 className="mb-3 text-sm font-bold text-foreground">')
a("        Yêu cầu chờ duyệt ({items.length})")
a("      </h3>")
a('      ' + T(d, 'className="space-y-3"'))
a("        {items.slice(0, 5).map((b) => (")
a('          ' + T(d, 'key={b.id} className="rounded-xl border border-amber-200/80 bg-amber-50/50 p-3"'))
a('            <p className="text-sm font-semibold text-foreground line-clamp-2">{b.reason}</p>')
a('            <p className="mt-1 text-xs text-muted-foreground">')
a("              {b.userName} · {formatDateVi(b.date)} · {padTime(b.timeFrom).replace(/:/g, 'h')}–")
a("              {padTime(b.timeTo).replace(/:/g, 'h')}")
a("            </p>")
a('            <p className="text-xs text-muted-foreground">{b.room}</p>')
a('            ' + T(d, 'className="mt-3 flex gap-2"'))
a("              <button")
a('                type="button"')
a("                disabled={!!processingId}")
a("                onClick={() => onReject(b.id)}")
a('                className="flex-1 rounded-lg border border-rose-200 bg-white py-1.5 text-xs font-semibold text-rose-600 hover:bg-rose-50 disabled:opacity-50"')
a("              >")
a("                Từ chối")
a("              </button>")
a("              <button")
a('                type="button"')
a("                disabled={!!processingId}")
a("                onClick={() => onApprove(b.id)}")
a('                className="flex flex-1 items-center justify-center gap-1 rounded-lg bg-emerald-600 py-1.5 text-xs font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"')
a("              >")
a("                {processingId === b.id ? (")
a('                  <Loader2 className="h-3 w-3 animate-spin" />')
a("                ) : (")
a('                  <CheckCircle2 className="h-3 w-3" />')
a("                )}")
a("                Duyệt")
a("              </button>")
a('            ' + TC(d))
a('          ' + TC(d))
a("        ))}")
a('      ' + TC(d))
a('    ' + TC(d))
a("  )")
a("}")
a("")
a("type RecentProps = { items: MeetingBooking[] }")
a("")
a("export function RoomBookingRecentPanel({ items }: RecentProps) {")
a("  return (")
a('    ' + T(d, 'className="rounded-2xl border border-border/60 bg-card p-4"'))
a('      <h3 className="mb-3 text-sm font-bold text-foreground">Gần đây</h3>')
a("      {items.length === 0 ? (")
a('        <p className="text-xs text-muted-foreground">Chưa có hoạt động.</p>')
a("      ) : (")
a('        ' + T(d, 'className="space-y-3"'))
a("          {items.map((b) => (")
a('            ' + T(d, 'key={b.id} className="flex gap-2 border-b border-border/40 pb-3 last:border-0 last:pb-0"'))
a('              <Clock className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />')
a('              ' + T(d, 'className="min-w-0 flex-1"'))
a('                <p className="truncate text-sm font-medium text-foreground">{b.reason}</p>')
a('                <p className="text-xs text-muted-foreground">')
a("                  {b.userName} · {b.room}")
a("                </p>")
a('              ' + TC(d))
a('            ' + TC(d))
a("          ))}")
a('        ' + TC(d))
a("      )}")
a('    ' + TC(d))
a("  )")
a("}")

# fix accidental corruption
text = '\n'.join(lines) + '\n'
text = text.replace('<motion-safe:animate-spin" />', '<' + d + ' className="space-y-3">')
text = text.replace('motion-safe:animate-spin" />', 'div')  # noop if any left
open(path, 'w').write(text)
print('ok')
