#!/usr/bin/env python3
path = '/Users/macbook/TalentManagement/TalentManagement_FE/src/features/room-booking/RoomScheduleTimeline.tsx'
ot, ct = chr(60), chr(62)

def T(name, attrs=''):
    return f'{ot}{name}{(" " + attrs) if attrs else ""}{ct}'

def TC(name):
    return f'{ot}/{name}{ct}'

div = 'div'
lines = []

def a(s):
    lines.append(s)

a("import { useMemo } from 'react'")
a("import type { MeetingBooking } from './api'")
a("import {")
a("  MEETING_ROOMS,")
a("  TIMELINE_END_HOUR,")
a("  TIMELINE_HOURS,")
a("  TIMELINE_START_HOUR,")
a("} from './roomBookingConstants'")
a("import { getBookingBlockClasses } from './roomBookingStyles'")
a("import {")
a("  hourSlotEnd,")
a("  hourSlotStart,")
a("  padTime,")
a("  timeToMinutes,")
a("  timeToPercent,")
a("} from './roomBookingTimeUtils'")
a("")
a("const ROW_LABEL_W = 140")
a("const HOUR_COL_MIN = 56")
a("")
a("type Props = {")
a("  viewDate: string")
a("  bookings: MeetingBooking[]")
a("  vnTime: { date: string; time: string }")
a("  onEmptySlotClick: (room: string, timeFrom: string, timeTo: string) => void")
a("  onBookingClick: (booking: MeetingBooking) => void")
a("}")
a("")
a("function bookingOverlapsTimeline(b: MeetingBooking): boolean {")
a("  const from = timeToMinutes(b.timeFrom)")
a("  const to = timeToMinutes(b.timeTo)")
a("  const start = TIMELINE_START_HOUR * 60")
a("  const end = TIMELINE_END_HOUR * 60")
a("  return to > start && from < end")
a("}")
a("")
a("export function RoomScheduleTimeline({")
a("  viewDate,")
a("  bookings,")
a("  vnTime,")
a("  onEmptySlotClick,")
a("  onBookingClick,")
a("}: Props) {")
a("  const showNowLine = viewDate === vnTime.date")
a("  const nowPercent = timeToPercent(vnTime.time)")
a("")
a("  const byRoom = useMemo(() => {")
a("    const map = new Map<string, MeetingBooking[]>()")
a("    for (const room of MEETING_ROOMS) {")
a("      map.set(")
a("        room.id,")
a("        bookings.filter((b) => b.room === room.id && bookingOverlapsTimeline(b)),")
a("      )")
a("    }")
a("    return map")
a("  }, [bookings])")
a("")
a("  const gridMinWidth = TIMELINE_HOURS.length * HOUR_COL_MIN")
a("  const spanHours = TIMELINE_END_HOUR - TIMELINE_START_HOUR")
a("")
a("  return (")
a('    ' + T(div, 'className="rounded-2xl border border-border/60 bg-card overflow-hidden"'))
a('      ' + T(div, 'className="relative overflow-x-auto"'))
a('        ' + T(div, 'style={{ minWidth: ROW_LABEL_W + gridMinWidth }}'))
a('          ' + T(div, 'className="flex border-b border-border/60"'))
a('            ' + T(div, 'className="shrink-0 border-r border-border/60 bg-muted/30 px-3 py-2" style={{ width: ROW_LABEL_W }}'))
a('            ' + T(div, 'className="flex"'))
a("              {TIMELINE_HOURS.map((h) => (")
a('                ' + T(div, 'key={h} className="flex shrink-0 items-center justify-center border-r border-border/40 py-2 text-xs font-semibold text-muted-foreground" style={{ width: HOUR_COL_MIN }}'))
a("                  {String(h).padStart(2, '0')}:00")
a('                ' + TC(div))
a("              ))}")
a('            ' + TC(div))
a('          ' + TC(div))
a("")
a("          {MEETING_ROOMS.map((room) => {")
a("            const roomBookings = byRoom.get(room.id) ?? []")
a("            return (")
a('              ' + T(div, 'key={room.id} className="flex border-b border-border/40 last:border-b-0"'))
a('                ' + T(div, 'className="flex shrink-0 flex-col justify-center border-r border-border/60 bg-muted/20 px-3 py-4" style={{ width: ROW_LABEL_W }}'))
a('                  <p className="text-sm font-bold text-foreground">{room.label}</p>')
a('                  <p className="text-xs text-muted-foreground">({room.seats} chỗ)</p>')
a('                ' + TC(div))
a('')
a('                ' + T(div, 'className="relative h-[88px] flex-1" style={{ minWidth: gridMinWidth }}'))
a('                  ' + T(div, 'className="absolute inset-0 grid" style={{ gridTemplateColumns: `repeat(${spanHours}, 1fr)` }}'))
a("                    {Array.from({ length: spanHours }, (_, i) => TIMELINE_START_HOUR + i).map(")
a("                      (h) => (")
a("                        <button")
a("                          key={h}")
a('                          type="button"')
a('                          className="h-full border-r border-slate-100/80 hover:bg-primary/5"')
a("                          title={`Đặt phòng ${room.label} lúc ${hourSlotStart(h)}`}")
a("                          onClick={() =>")
a("                            onEmptySlotClick(room.id, hourSlotStart(h), hourSlotEnd(h))")
a("                          }")
a("                        />")
a("                      ),")
a("                    )}")
a('                  ' + TC(div))
a("")
a("                  {roomBookings.map((b) => {")
a("                    const left = timeToPercent(b.timeFrom)")
a("                    const right = timeToPercent(b.timeTo)")
a("                    const width = Math.max(4, right - left)")
a("                    return (")
a("                      <button")
a("                        key={b.id}")
a('                        type="button"')
a('                        className={`absolute top-2 bottom-2 z-10 overflow-hidden rounded-lg border px-2 py-1.5 text-left transition hover:ring-2 hover:ring-primary/40 ${getBookingBlockClasses(b)}`}')
a("                        style={{ left: `${left}%`, width: `${width}%` }}")
a("                        onClick={(e) => {")
a("                          e.stopPropagation()")
a("                          onBookingClick(b)")
a("                        }}")
a("                      >")
a('                        <p className="truncate text-[11px] font-bold leading-tight">')
a("                          {b.reason}")
a("                        </p>")
a('                        <p className="truncate text-[10px] opacity-80">{b.userName}</p>')
a('                        <p className="text-[10px] font-semibold opacity-90">')
a("                          {padTime(b.timeFrom).replace(/:/g, 'h')} –{' '}")
a("                          {padTime(b.timeTo).replace(/:/g, 'h')}")
a("                        </p>")
a("                      </button>")
a("                    )")
a("                  })}")
a('                ' + TC(div))
a('              ' + TC(div))
a("            )")
a("          })}")
a("")
a("          {showNowLine && nowPercent >= 0 && nowPercent <= 100 && (")
a('            ' + T(div, 'className="pointer-events-none absolute bottom-0 top-[41px] z-20 w-0.5 bg-rose-500" style={{ left: ROW_LABEL_W + (gridMinWidth * nowPercent) / 100 }}'))
a('              <span className="absolute -left-4 -top-5 rounded bg-rose-500 px-1.5 py-0.5 text-[10px] font-bold text-white">')
a("                {padTime(vnTime.time).replace(/:/g, 'h')}")
a("              </span>")
a('            ' + TC(div))
a("          )}")
a('        ' + TC(div))
a('      ' + TC(div))
a("")
a('      <p className="border-t border-border/50 px-4 py-3 text-center text-xs text-muted-foreground">')
a("        Nhấp vào khung giờ trống để đặt phòng nhanh chóng")
a("      </p>")
a('    ' + TC(div))
a("  )")
a("}")

open(path, 'w').write('\n'.join(lines) + '\n')
print('ok')
